name: Build & Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  APP_NAME: "DepartureSound"
  NAMESPACE: "DepartureSound"
  TZ: "Asia/Tokyo"

jobs:
  calc_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: "Calc Version"
    outputs:
      VERSION: ${{ steps.calc_version.outputs.VERSION }}
      APP_PREFIX: ${{ steps.calc_version.outputs.APP_PREFIX }}
    steps:
      - name: Get latest release
        id: latest_release
        uses: actions/github-script@v7.0.1
        with:
          script: |
            try {
              const response = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              return response.data.tag_name;
            }
            catch (e){
              if (e.status === 404) {
                return '';
              } else {
                throw e;
              }
            }

      - name: Calculate Version
        id: calc_version
        run: |
          latest_tag="${{ steps.latest_release.outputs.result }}"
          today=$(date +%Y%m%d)

          if [ -n "${latest_tag}" ] && [[ "${latest_tag}" == *"$today"* ]]; then
            n=$(echo "$latest_tag" | awk -F. '{print $4}')
            n=$((n + 1))
          else
            n=1
          fi

          VERSION="v1.0.${today}.${n}"

          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

          file_name_version=$(echo "$VERSION" | sed 's/\./_/g')
          echo "APP_PREFIX=${{ env.APP_NAME }}_${file_name_version}" >> "$GITHUB_OUTPUT"

  build:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    needs: calc_version
    name: "Build"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Generate ServerAddress.cs
        shell: pwsh
        run: |
          $content = @"
          namespace ${{ env.NAMESPACE }};
          public static class ServerAddress {
              public const string SignalAddress = "${{ secrets.SERVER_ADDRESS }}";
              public const string Version = "${{ needs.calc_version.outputs.VERSION }}";
          }
          "@
          $content | Out-File -FilePath "./ServerAddress.cs" -Encoding utf8

      - name: Restore NuGet packages
        run: nuget restore "車掌用知らせ灯.sln"

      - name: Build with MSBuild
        run: msbuild "車掌用知らせ灯.sln" /p:Configuration=Release /p:Platform="Any CPU"

      - name: Zip output
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "./bin/Release/*" `
            -DestinationPath "${{ needs.calc_version.outputs.APP_PREFIX }}.zip"

      - name: Upload ZIP (artifact)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ needs.calc_version.outputs.APP_PREFIX }}.zip
          path: ./${{ needs.calc_version.outputs.APP_PREFIX }}.zip

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: "Create Release"
    needs:
      - calc_version
      - build
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.2.1
        with:
          path: out
          pattern: "**/*.zip"
          merge-multiple: true  # ZIP を out/直下に展開

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ needs.calc_version.outputs.VERSION }}
          files: out/*.zip
          make_latest: true
          prerelease: false